name: Deploy

on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout the repo
      uses: actions/checkout@v2

    - name: Publish Docker
      uses: docker/build-push-action@v1
      with:
        repository: trecnoc/nexus3-custom
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest
